name       : VisualBoyAdvance-M
version    : 2.1.5
release    : 24
source     :
    - https://github.com/visualboyadvance-m/visualboyadvance-m/archive/refs/tags/v2.1.5.tar.gz : 5ece12815f0a6d2ee70ebcdbc072bb0885184e3c89332c2bdeba03c779a2329a
license    : GPL-2.0-or-later
component  : games.emulator
summary    : Nintendo Game Boy Advance Emulator
description: |
    An open-source Nintendo Game Boy, Super Game Boy, Game Boy Advance Emulators.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(glu)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libavcodec)
    - pkgconfig(libpng)
    - pkgconfig(libturbojpeg)
    - pkgconfig(openal)
    - pkgconfig(sdl2)
    - pkgconfig(sfml-network)
    - wxwidgets-devel
setup      : |
    %cmake . -DCMAKE_BUILD_TYPE=Release -DENABLE_FFMPEG=ON -DENABLE_LINK=TRUE -DCMAKE_SKIP_RPATH=TRUE -DENABLE_LTO=OFF
build      : |
    %make
install    : |
    %make_install
