name       : VisualBoyAdvance-M
version    : 2.1.4
release    : 20
source     :
    - git|https://github.com/visualboyadvance-m/visualboyadvance-m.git : 09fbcbac07148ea32add848722dab34a7eb4f6b5
license    : GPL-2.0-or-later
component  : games.emulator
summary    : Nintendo Game Boy Advance Emulator
description: |
    An open-source Nintendo Game Boy, Super Game Boy, Game Boy Advance Emulators.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(glu)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libavcodec)
    - pkgconfig(libpng)
    - pkgconfig(libturbojpeg)
    - pkgconfig(openal)
    - pkgconfig(sdl2)
    - pkgconfig(sfml-network)
    - wxwidgets-devel
setup      : |
    %cmake . -DCMAKE_BUILD_TYPE=Release -DENABLE_FFMPEG=ON -DENABLE_LINK=TRUE -DCMAKE_SKIP_RPATH=TRUE -DENABLE_LTO=OFF
build      : |
    %make
install    : |
    %make_install
