name       : VisualBoyAdvance-M
version    : 2.1.3
release    : 16
source     :
    - https://github.com/visualboyadvance-m/visualboyadvance-m/archive/v2.1.3.tar.gz : c64a8b400e9af862e0be74148760a7c73f98d08dcbb7d01eca81e6dc5ad376fd
license    : GPL-2.0-or-later
component  : games.emulator
summary    : Nintendo Game Boy Advance Emulator
description: |
    An open-source Nintendo Game Boy, Super Game Boy, Game Boy Advance Emulators.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(glu)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libpng)
    - pkgconfig(libturbojpeg)
    - pkgconfig(openal)
    - pkgconfig(sdl2)
    - pkgconfig(sfml-network)
    - wxwidgets-devel
setup      : |
    %cmake . -DCMAKE_BUILD_TYPE=Release -DENABLE_FFMPEG=OFF -DENABLE_LINK=TRUE -DCMAKE_SKIP_RPATH=TRUE -DENABLE_LTO=OFF
build      : |
    %make
install    : |
    %make_install
