name       : VisualBoyAdvance-M
version    : 2.0.1
release    : 12
source     :
    - http://dl.vba-m.com/2.0.1/visualboyadvance-m-2.0.1.tar.gz : 0204787317311cf6dd08e28f2dff4f52cdb97356dd851b96a9054abe4281143e
license    : GPL-2.0-or-later
component  : games.emulator
summary    : Nintendo Game Boy Advance Emulator
description: |
    An open-source Nintendo Game Boy, Super Game Boy, Game Boy Advance Emulators.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(glu)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libpng)
    - pkgconfig(libturbojpeg)
    - pkgconfig(openal)
    - pkgconfig(sdl2)
    - pkgconfig(sfml-network)
    - wxwidgets-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-add-changelog.patch
    %patch -p1 < $pkgfiles/0002-commit-fix.patch
    %cmake . -DCMAKE_BUILD_TYPE=Release -DENABLE_FFMPEG=OFF -DENABLE_LINK=TRUE -DCMAKE_SKIP_RPATH=TRUE -DENABLE_LTO=OFF
build      : |
    %make
install    : |
    %make_install
