name       : VisualBoyAdvance-M
version    : 2.0.0
release    : 5
source     :
    - https://github.com/visualboyadvance-m/visualboyadvance-m/archive/Beta-3.tar.gz : 100176bdf31f27211876bac72a297e5545189aebf74c8fe7ddf5a943a39e79b0
license    : GPL-2.0
component  : games.emulator
summary    : Nintendo Game Boy Advance Emulator.
description: |
    An open-source Nintendo Game Boy, Super Game Boy, Game Boy Advance Emulators.
builddeps  :
    - pkgconfig(sfml-network)
    - pkgconfig(libpng)
    - pkgconfig(sdl2)
    - pkgconfig(cairo)
    - pkgconfig(openal)
    - pkgconfig(gl)
    - pkgconfig(glu)
    - libjpeg-turbo-devel
    - wxwidgets-devel
setup      : |
    %cmake . -DCMAKE_BUILD_TYPE=Release -DENABLE_FFMPEG=OFF -DENABLE_LINK=TRUE -DCMAKE_SKIP_RPATH=TRUE -DENABLE_LTO=OFF -DVERSION="2.0.0 Beta 3"
build      : |
    %make
install    : |
    %make_install
