name       : VisualBoyAdvance-M
version    : 2.1.6
release    : 25
source     :
    - https://github.com/visualboyadvance-m/visualboyadvance-m/archive/refs/tags/v2.1.6.tar.gz : 056d4482bdd297445a63d496079e0b0cf381951cd5ef8ce308750c7738946fca
license    : GPL-2.0-or-later
component  : games.emulator
summary    : Nintendo Game Boy Advance Emulator
description: |
    An open-source Nintendo Game Boy, Super Game Boy, Game Boy Advance Emulators.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(glu)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libavcodec)
    - pkgconfig(libpng)
    - pkgconfig(libturbojpeg)
    - pkgconfig(openal)
    - pkgconfig(sdl2)
    - pkgconfig(sfml-network)
    - wxwidgets-devel
setup      : |
    %cmake . -DCMAKE_BUILD_TYPE=Release -DENABLE_FFMPEG=ON -DENABLE_LINK=TRUE -DCMAKE_SKIP_RPATH=TRUE -DENABLE_LTO=OFF
build      : |
    %make
install    : |
    %make_install
