name       : VisualBoyAdvance-M
version    : 2.0.0
release    : 3
source     :
    - https://github.com/visualboyadvance-m/visualboyadvance-m/archive/v2.0.0.tar.gz : 65ac5745442bf086d7cfa7114bf1b94e9801775019de683489787a442de398e3
license    : GPL-2.0
component  : games.emulator
summary    : Nintendo Game Boy Advance Emulator.
description: |
    An open-source Nintendo Game Boy, Super Game Boy, Game Boy Advance Emulators.
builddeps  : 
    - pkgconfig(sfml-network)
    - pkgconfig(libpng)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(atkmm-1.6)
    - pkgconfig(sdl2)
    - pkgconfig(cairo)
    - pkgconfig(openal)
    - pkgconfig(gl)
    - pkgconfig(glu)
    - libjpeg-turbo-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-some-compile-issues-and-desktop-launcher-issues.patch
    %cmake . -DCMAKE_BUILD_TYPE=Release -DENABLE_WX=OFF -DENABLE_GTK3=ON -DENABLE_SDL=OFF -DENABLE_LINK=TRUE -DCMAKE_SKIP_RPATH=TRUE -DVERSION="2.0.0 Beta 2"
build      : |
    %make
install    : |
    %make_install
